# -*- coding: utf-8 -*-
"""Midterm

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QQrcU_Y3zW8zHfmRJIOwjmELcFpmSMDW
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import seaborn as sns

import matplotlib.pyplot as plt

df =pd.read_csv('/content/drive/MyDrive/unemployment_rate_data.csv')

df.head()
df.info()

sns.heatmap(df.isnull(),cbar=False)

import matplotlib.pyplot as plt 
import seaborn as sn

color = sns.color_palette()
df = df.groupby(["unrate_women"])["unrate_men"].aggregate("mean").reset_index()
plt.figure(figsize=(12,8))
sns.pointplot(df['unrate_women'].values, df['unrate_men'].values, alpha=0.8, color=color[2])
plt.ylabel('unrate_men', fontsize=12)
plt.xlabel('unrate_women', fontsize=12)
plt.title("uneemployement_rate_average", fontsize=15)
plt.xticks(rotation='horizontal')
plt.show()

labels = ['G1', 'G2', 'G3', 'G4', 'G5']
unrate_men_means = [20, 34, 30, 35, 27]
unrate_women_means = [25, 32, 34, 20, 25]
x_vals = range(len(men_means))
plt.figure()
plt.barh(x_vals, men_means, height=0.3, color='c', label='Men')
plt.barh(x_vals, women_means, left=men_means, height=0.3, color='r', label='Women')
ax = plt.gca()
#ax.set_yticks(x)
ax.set_yticklabels(labels)
ax.legend()

plt.figure()
plt.hist(df['unrate_men'], bins=10)

